/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_fileclass_FCClientSocket_Java */

#ifndef _FC_FCClientSocket_Java
#define _FC_FCClientSocket_Java
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_fileclass_FCClientSocket_Java
 * Method:    addDevice
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_fileclass_FCClientSocket_1Java_addDevice
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
