/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_Interface_FCJInterface */

#ifndef _Included_com_example_Interface_FCJInterface
#define _Included_com_example_Interface_FCJInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_Interface_FCJInterface
 * Method:    checkUserNameAndPassWord
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_Interface_FCJInterface_checkUserNameAndPassWord
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_example_Interface_FCJInterface
 * Method:    getData
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_Interface_FCJInterface_getData
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
