APP_STL := gnustl_static

APP_CFLAGS := $(BUILD_FLAGS)
APP_CPPFLAGS := $(BUILD_FLAGS) -fsigned-char -frtti -std=c++11

RELEASE_FLAGS = -DFR_RELEASE -DFC_PLATFORM=2

APP_CFLAGS += $(RELEASE_FLAGS)
APP_CPPFLAGS += $(RELEASE_FLAGS)

#APP_OPTIM := debug

APP_ABI := armeabi armeabi-v7a

APP_PLATFORM := android-9
NDK_TOOLCHAIN_VERSION := 4.6
